// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anmadaditlpkedmaeibx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubWFkYWRpdGxwa2VkbWFlaWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTc0NjIsImV4cCI6MjA3MjA5MzQ2Mn0.W-rcPqng4qizzy0T1XzLzRlQlX3D5iyBnSnNrnZE94o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});