# Debug workflow to test Lighthouse CI setup
name: Debug Lighthouse CI

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          echo "Building application..."
          npm run build
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          echo "✅ Build completed successfully"
          ls -la dist/

      - name: Test preview server
        run: |
          echo "Testing preview server startup..."
          # Start server in background
          npm run preview -- --port 4173 --host &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"

          # Wait for server to start
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -f http://localhost:4173/ > /dev/null 2>&1; then
              echo "✅ Server is responding"
              break
            fi
            echo "Attempt $i/30 - waiting..."
            sleep 2
          done

          # Test server response
          curl -f http://localhost:4173/ || echo "❌ Server not responding"

          # Cleanup
          echo "Cleaning up server process..."
          kill $SERVER_PID || echo "Process already terminated"
          wait $SERVER_PID 2>/dev/null || true

      - name: Start debug server for LHCI
        run: |
          echo "Starting debug server for Lighthouse CI..."
          npm run preview -- --port 4173 --host &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV

          # Wait and test server
          for i in {1..20}; do
            if curl -f -s http://localhost:4173/ > /dev/null 2>&1; then
              echo "✅ Debug server ready"
              break
            fi
            echo "Waiting for debug server... ($i/20)"
            sleep 3
          done

          # Test server response
          echo "Testing server response:"
          curl -I http://localhost:4173/ || echo "Server not responding"

      - name: Run Lighthouse CI with debug
        run: |
          echo "Running Lighthouse CI..."
          echo "Config contents:"
          cat lighthouserc.json
          echo "Testing URL accessibility:"
          curl -f http://localhost:4173/ | head -20 || echo "URL not accessible"

          npx lhci autorun --config=lighthouserc.json
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.ref_name }}

      - name: Cleanup debug server
        if: always()
        run: |
          if [ -n "$SERVER_PID" ]; then
            echo "Stopping debug server"
            kill $SERVER_PID || true
            wait $SERVER_PID 2>/dev/null || true
          fi