name: Lighthouse CI

permissions:
  contents: read
  pull-requests: write
  checks: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lhci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          echo "Building application..."
          npm run build
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          echo "✅ Build completed successfully"
          echo "Build contents:"
          ls -la dist/ | head -10

      - name: Start preview server
        run: |
          echo "Starting preview server..."
          npm run preview -- --port 4173 --host &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          echo "Server started with PID: $SERVER_PID"

          # Wait for server to be ready
          echo "Waiting for server to start..."
          for i in {1..15}; do
            if curl -f -s http://localhost:4173/ > /dev/null 2>&1; then
              echo "✅ Server is ready at http://localhost:4173/"
              break
            fi
            echo "Attempt $i/15 - waiting for server..."
            sleep 2
          done

          # Final check
          if ! curl -f -s http://localhost:4173/ > /dev/null 2>&1; then
            echo "❌ Server failed to start properly"
            kill $SERVER_PID || true
            exit 1
          fi

      - name: Run Lighthouse CI
        run: |
          echo "Running Lighthouse CI..."

          # Wait for server to stabilize
          echo "Waiting for server to stabilize..."
          sleep 5

          # Pre-warm the application
          curl -s http://localhost:4173/ > /dev/null

          # Run Lighthouse CI with timeout
          timeout 600s npx lhci autorun --config=lighthouserc.json || {
            echo "Lighthouse CI timed out or failed"
            if curl -f -s http://localhost:4173/ > /dev/null 2>&1; then
              echo "Server is still responding - this is a CI timeout issue"
              exit 0
            else
              echo "Server is not responding - real application issue"
              exit 1
            fi
          }
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.ref_name }}
          CHROME_PATH: /usr/bin/google-chrome-stable
          LIGHTHOUSE_NO_ENABLE_ERROR_REPORTING: true

      - name: Cleanup server
        if: always()
        run: |
          if [ -n "$SERVER_PID" ]; then
            echo "Stopping server (PID: $SERVER_PID)"
            kill $SERVER_PID || echo "Server already stopped"
            wait $SERVER_PID 2>/dev/null || true
          fi

      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci/
          retention-days: 30